"use client";

import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { BarChart3, Bookmark, BrainCircuit, ChevronRight, Code2, Database, FlaskConical, Gauge, Home, Layers3, Search, ShieldCheck, Sparkles, TerminalSquare, Trophy, WandSparkles } from "lucide-react";
import { demoQuestions, type DemoQuestion } from "@/lib/demo-data";

type View = "dashboard"|"questions"|"python"|"sql"|"quiz"|"scenarios"|"search"|"progress"|"admin"|"bookmarks"|"paths";
const nav: {id:View;label:string;icon:any}[] = [
  {id:"dashboard",label:"Dashboard",icon:Home},{id:"questions",label:"Question Bank",icon:Layers3},
  {id:"python",label:"Python Lab",icon:Code2},{id:"sql",label:"SQL Lab",icon:Database},
  {id:"quiz",label:"MCQ Arena",icon:FlaskConical},{id:"scenarios",label:"DE Scenarios",icon:BrainCircuit},
  {id:"search",label:"Semantic Search",icon:Search},{id:"progress",label:"Progress",icon:BarChart3},
  {id:"paths",label:"Learning Paths",icon:Trophy},{id:"bookmarks",label:"Bookmarks",icon:Bookmark},{id:"admin",label:"Admin",icon:ShieldCheck},
];
const difficultyStyle: Record<string,string> = {Easy:"text-emerald-300 bg-emerald-400/10",Medium:"text-amber-300 bg-amber-400/10",Hard:"text-rose-300 bg-rose-400/10"};

function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl border border-white/10 bg-white/[.035] shadow-[0_20px_70px_rgba(0,0,0,.18)] ${className}`}>{children}</div>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full border border-white/10 bg-white/[.045] px-2.5 py-1 text-xs text-slate-300">{children}</span>}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <Card className="p-5"><div className="text-xs uppercase tracking-[.18em] text-slate-500">{label}</div><div className="mt-2 text-3xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-sm text-slate-400">{sub}</div></Card>}

function QuestionList({questions,onOpen}:{questions:DemoQuestion[];onOpen:(q:DemoQuestion)=>void}){return <div className="overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[100px_1fr_110px_120px] bg-white/[.04] px-4 py-3 text-xs uppercase tracking-wider text-slate-500"><span>ID</span><span>Problem</span><span>Difficulty</span><span>Topic</span></div>{questions.map(q=><button key={q.id} onClick={()=>onOpen(q)} className="grid w-full grid-cols-[100px_1fr_110px_120px] items-center border-t border-white/10 px-4 py-3 text-left transition hover:bg-white/[.045]"><span className="font-mono text-xs text-slate-500">{q.id}</span><span className="pr-4 text-sm font-medium text-slate-100">{q.title}</span><span><span className={`rounded-full px-2 py-1 text-xs ${difficultyStyle[q.difficulty]}`}>{q.difficulty}</span></span><span className="text-xs text-slate-400">{q.topic}</span></button>)}</div>}

function Workspace({question,mode,onBack}:{question:DemoQuestion;mode:"python"|"sql";onBack:()=>void}){
  const starter = mode==="python" ? "def solve(values):\n    # Write your solution\n    pass\n" : "SELECT\n  -- Write your query\nFROM facts;";
  const [code,setCode]=useState(starter); const [result,setResult]=useState("Ready"); const [tab,setTab]=useState<"problem"|"solution">("problem");
  const run=()=>{setResult("Running isolated demo checks…");setTimeout(()=>setResult(mode==="python"?"✓ 4/4 public tests passed · 38 ms":"✓ Query executed · 2 rows · 21 ms"),450)};
  return <div className="space-y-4"><button onClick={onBack} className="text-sm text-cyan-300">← Back to question bank</button><div className="grid min-h-[680px] gap-4 xl:grid-cols-[.92fr_1.08fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><div className="text-xs text-slate-500">{question.id}</div><h2 className="mt-1 font-semibold">{question.title}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs ${difficultyStyle[question.difficulty]}`}>{question.difficulty}</span></div><div className="flex gap-2 border-b border-white/10 px-4 py-2"><button onClick={()=>setTab("problem")} className={`rounded-lg px-3 py-1.5 text-sm ${tab==="problem"?"bg-white/10":"text-slate-400"}`}>Problem</button><button onClick={()=>setTab("solution")} className={`rounded-lg px-3 py-1.5 text-sm ${tab==="solution"?"bg-white/10":"text-slate-400"}`}>Solution</button></div><div className="sf-scroll max-h-[590px] overflow-auto p-5"><div className="markdownish whitespace-pre-wrap text-sm leading-7 text-slate-300">{tab==="problem"?question.description:question.explanation}</div></div></Card><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 p-4"><div className="flex items-center gap-2"><TerminalSquare size={17} className="text-cyan-300"/><span className="font-medium">{mode==="python"?"Python 3.13":"PostgreSQL 18"}</span></div><div className="flex gap-2"><button onClick={()=>setCode(starter)} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-slate-300">Reset</button><button onClick={run} className="rounded-lg bg-cyan-300 px-4 py-1.5 text-xs font-semibold text-slate-950">Run</button></div></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} className="h-[480px] w-full resize-none bg-[#04090d] p-5 font-mono text-sm leading-6 text-slate-200 outline-none"/><div className="border-t border-white/10 p-4"><div className="mb-2 text-xs uppercase tracking-wider text-slate-500">Execution</div><div className="rounded-xl bg-black/30 p-3 font-mono text-sm text-emerald-300">{result}</div></div></Card></div></div>
}

export function SkillForgeApp({initialView}:{initialView:View}){
  const [view,setView]=useState<View>(initialView); const [query,setQuery]=useState(""); const [topic,setTopic]=useState("All"); const [selected,setSelected]=useState<DemoQuestion|null>(null);
  const filtered=useMemo(()=>demoQuestions.filter(q=>(topic==="All"||q.topic===topic)&&(`${q.title} ${q.description} ${q.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[query,topic]);
  const open=(q:DemoQuestion)=>{if(q.language==="python"){setSelected(q);setView("python")} else if(q.language==="sql"){setSelected(q);setView("sql")} else {setSelected(q);setView(q.type.toLowerCase().includes("mcq")?"quiz":"scenarios")}};
  if((view==="python"||view==="sql")&&selected) return <Shell view={view} setView={setView}><Workspace question={selected} mode={view} onBack={()=>{setSelected(null);setView("questions")}}/></Shell>;
  return <Shell view={view} setView={setView}>
    {view==="dashboard"&&<Dashboard onGo={setView}/>} 
    {view==="questions"&&<section><Header eyebrow="24,800 SOURCE-BACKED RECORDS" title="Question Bank" copy="Search real imported content across coding, architecture, cloud, certification, and enterprise data-engineering scenarios."/><div className="mb-4 grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-500" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, body, tags…" className="w-full rounded-xl border border-white/10 bg-white/[.035] py-3 pl-10 pr-4 outline-none focus:border-cyan-300/50"/></div><select value={topic} onChange={e=>setTopic(e.target.value)} className="rounded-xl border border-white/10 bg-[#0c1822] px-4"><option>All</option><option>Python</option><option>SQL</option><option>Snowflake</option></select></div><QuestionList questions={filtered} onOpen={open}/></section>}
    {view==="quiz"&&<Quiz question={selected?.type.toLowerCase().includes("mcq")?selected:demoQuestions.find(x=>x.id==="SF-ARCH-0001")!}/>} 
    {view==="scenarios"&&<Scenario question={selected?.id.startsWith("ENT-")?selected:demoQuestions.find(x=>x.id==="ENT-0001")!}/>} 
    {view==="search"&&<SemanticSearch/>}{view==="progress"&&<Progress/>}{view==="admin"&&<Admin/>}{view==="bookmarks"&&<QuestionList questions={demoQuestions.slice(0,4)} onOpen={open}/>} {view==="paths"&&<Paths onGo={setView}/>} 
    {(view==="python"||view==="sql")&&!selected&&<section><Header eyebrow="PRACTICE LAB" title={`${view==="python"?"Python":"SQL"} workspace`} copy="Choose a source-backed problem to open the editor."/><QuestionList questions={demoQuestions.filter(q=>q.language===view)} onOpen={open}/></section>}
  </Shell>
}

function Shell({view,setView,children}:{view:View;setView:(v:View)=>void;children:React.ReactNode}){return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#071018]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between px-4 lg:px-6"><button onClick={()=>setView("dashboard")} className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 to-blue-400 font-black text-slate-950">S</div><div className="text-left"><div className="font-semibold">SkillForge <span className="text-cyan-300">AI</span></div><div className="text-[10px] uppercase tracking-[.22em] text-slate-500">Interview Intelligence</div></div></button><div className="flex items-center gap-3"><div className="hidden rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs text-emerald-300 sm:block">24,800 records indexed</div><button className="rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-300">Demo User</button></div></div></header><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[230px_1fr]"><aside className="hidden min-h-[calc(100vh-64px)] border-r border-white/10 p-3 lg:block">{nav.map(n=>{const I=n.icon; return <button key={n.id} onClick={()=>setView(n.id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${view===n.id?"bg-cyan-300/10 text-cyan-200":"text-slate-400 hover:bg-white/[.04] hover:text-slate-200"}`}><I size={17}/>{n.label}</button>})}</aside><main className="min-w-0 p-4 md:p-6 xl:p-8">{children}</main></div></div>}
function Header({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="mb-6"><div className="text-xs font-semibold tracking-[.2em] text-cyan-300">{eyebrow}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{copy}</p></div>}
function Dashboard({onGo}:{onGo:(v:View)=>void}){return <section><Header eyebrow="SKILLFORGE COMMAND CENTER" title="Train for the interview you actually want." copy="A source-backed preparation workspace spanning coding, data engineering, cloud, system design, and AI architecture."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Question corpus" value="24,800" sub="22 curated banks"/><Stat label="Enterprise scenarios" value="1,800" sub="1,090 include code"/><Stat label="SQL + Python" value="5,000" sub="coding problems"/><Stat label="Readiness" value="72%" sub="+6 points this week"/></div><div className="mt-6 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card className="p-6"><div className="flex items-center justify-between"><div><div className="text-sm text-slate-400">Recommended next</div><h2 className="mt-1 text-xl font-semibold">SQL window functions → Snowflake performance</h2></div><Sparkles className="text-cyan-300"/></div><div className="mt-5 grid gap-3 md:grid-cols-3">{[["SQL","3 problems","sql"],["Snowflake","2 architect MCQs","quiz"],["Scenario","Warehouse contention","scenarios"]].map(([a,b,v])=><button key={a} onClick={()=>onGo(v as View)} className="rounded-xl border border-white/10 bg-black/10 p-4 text-left hover:border-cyan-300/30"><div className="font-medium">{a}</div><div className="mt-1 text-xs text-slate-500">{b}</div><ChevronRight className="mt-4 text-slate-600" size={16}/></button>)}</div></Card><Card className="p-6"><div className="flex items-center gap-2"><Gauge className="text-blue-300" size={18}/><h2 className="font-semibold">Skill radar</h2></div><div className="mt-5 space-y-4">{[["SQL",84],["Python",77],["Snowflake",69],["System Design",58]].map(([n,v])=><div key={n as string}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-400">{n}</span><span>{v}%</span></div><div className="h-2 rounded-full bg-white/5"><div style={{width:`${v}%`}} className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-blue-400"/></div></div>)}</div></Card></div><div className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Continue practicing</h2><button onClick={()=>onGo("questions")} className="text-xs text-cyan-300">View all</button></div><QuestionList questions={demoQuestions.slice(0,5)} onOpen={()=>onGo("questions")}/></div></section>}
function Quiz({question}:{question:DemoQuestion}){const [choice,setChoice]=useState<string|null>(null);const correct="A";return <section><Header eyebrow="ARCHITECT MCQ" title={question.title} copy="Source-backed Snowflake architect question with immediate explanation."/><Card className="max-w-4xl p-6"><div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">{question.description.replace(/\n[A-D]\. /g,"\n\n")}</div><div className="mt-5 grid gap-2">{["A","B","C","D"].map(c=><button key={c} onClick={()=>setChoice(c)} className={`rounded-xl border p-3 text-left ${choice===c?(c===correct?"border-emerald-400/40 bg-emerald-400/10":"border-rose-400/40 bg-rose-400/10"):"border-white/10 bg-white/[.03]"}`}>Option {c}</button>)}</div>{choice&&<div className="mt-5 rounded-xl bg-black/20 p-4 text-sm text-slate-300">{choice===correct?"Correct. ":"Not quite. "}The architecture goal is independent compute isolation while retaining shared storage.</div>}</Card></section>}
function Scenario({question}:{question:DemoQuestion}){const [answer,setAnswer]=useState("");const [graded,setGraded]=useState(false);return <section><Header eyebrow="ENTERPRISE DATA ENGINEERING" title={question.title} copy="Work through production symptoms, evidence, blast radius, remediation, and validation."/><div className="grid gap-4 xl:grid-cols-[1fr_.8fr]"><Card className="p-6"><div className="sf-scroll max-h-[620px] overflow-auto whitespace-pre-wrap text-sm leading-7 text-slate-300">{question.description}</div></Card><Card className="p-6"><div className="mb-3 font-medium">Your investigation plan</div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="h-64 w-full rounded-xl border border-white/10 bg-black/20 p-4 text-sm outline-none focus:border-cyan-300/40" placeholder="Explain hypotheses, evidence, remediation, and regression checks…"/><button onClick={()=>setGraded(true)} className="mt-3 rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Evaluate response</button>{graded&&<div className="mt-4 rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4"><div className="text-sm font-semibold text-cyan-200">AI rubric · 82/100</div><ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-5 text-slate-400"><li>Strong blast-radius framing and evidence selection.</li><li>Add explicit workload isolation and warehouse sizing validation.</li><li>Call out cost/query-history comparison before and after remediation.</li></ul></div>}</Card></div></section>}
function SemanticSearch(){const [q,setQ]=useState("find Snowflake warehouse contention and cost optimization scenarios"); const matches=demoQuestions.filter(x=>x.topic==="Snowflake"||x.id.startsWith("ENT-")).slice(0,4);return <section><Header eyebrow="PGVECTOR + HYBRID SEARCH" title="Semantic Search" copy="The production path combines Postgres full-text search, pgvector similarity, and relational filters."/><Card className="p-4"><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} className="flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none"/><button className="rounded-xl bg-cyan-300 px-5 font-semibold text-slate-950">Search</button></div></Card><div className="mt-4 grid gap-3">{matches.map((m,i)=><Card key={m.id} className="p-5"><div className="flex justify-between gap-4"><div><div className="text-xs text-cyan-300">{m.id} · semantic match</div><div className="mt-1 font-medium">{m.title}</div><div className="mt-2 flex flex-wrap gap-2">{m.tags.slice(0,4).map(t=><Pill key={t}>{t}</Pill>)}</div></div><div className="text-lg font-semibold">{[.93,.89,.86,.81][i]}</div></div></Card>)}</div></section>}
function Progress(){return <section><Header eyebrow="PERSONALIZED LEARNING" title="Progress & readiness" copy="Attempts, correctness, topic mastery, streaks, and recommended next questions are persisted per user in Supabase."/><div className="grid gap-3 md:grid-cols-3"><Stat label="Solved" value="148" sub="32 this month"/><Stat label="Accuracy" value="78%" sub="+4% over 30 days"/><Stat label="Streak" value="12 days" sub="Personal best: 18"/></div><Card className="mt-4 p-6"><h2 className="font-semibold">Topic mastery</h2><div className="mt-5 space-y-4">{[["Python",77],["SQL",84],["Snowflake",69],["Data Engineering",72],["Cloud",61],["AI Architecture",56]].map(([n,v])=><div key={n as string} className="grid grid-cols-[150px_1fr_55px] items-center gap-3 text-sm"><span className="text-slate-400">{n}</span><div className="h-2 rounded-full bg-white/5"><motion.div initial={{width:0}} animate={{width:`${v}%`}} className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-blue-400"/></div><span className="text-right">{v}%</span></div>)}</div></Card></section>}
function Admin(){return <section><Header eyebrow="CONTENT OPERATIONS" title="Admin Intelligence Center" copy="Upload → validate → review → import → embed → publish. No source is silently promoted to published content."/><div className="grid gap-3 md:grid-cols-4"><Stat label="Imported" value="24,800" sub="normalized records"/><Stat label="Needs review" value="24,800" sub="rights-review disposition"/><Stat label="Embedding queue" value="0" sub="provider keys optional"/><Stat label="Import errors" value="0" sub="latest normalized corpus"/></div><Card className="mt-4 p-6"><h2 className="font-semibold">Import workflow</h2><div className="mt-5 grid gap-3 md:grid-cols-5">{["Upload","Validate","Review","Embed","Publish"].map((s,i)=><div key={s} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="text-xs text-slate-500">0{i+1}</div><div className="mt-1 font-medium">{s}</div><div className="mt-3 text-xs text-emerald-300">Ready</div></div>)}</div></Card></section>}
function Paths({onGo}:{onGo:(v:View)=>void}){return <section><Header eyebrow="GUIDED PREPARATION" title="Learning Paths" copy="Adaptive sequences can combine coding, MCQ, scenario, and architecture practice."/><div className="grid gap-4 md:grid-cols-3">{[["Data Engineer","SQL → Python → Spark → Airflow","questions"],["Snowflake Architect","Core → Performance → Security → Design","quiz"],["AI Data Architect","RAG → Agents → Governance → System Design","scenarios"]].map(([a,b,v])=><Card key={a} className="p-5"><div className="mb-8 grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><WandSparkles size={19}/></div><h2 className="font-semibold">{a}</h2><p className="mt-2 text-sm text-slate-400">{b}</p><button onClick={()=>onGo(v as View)} className="mt-5 text-sm text-cyan-300">Open path →</button></Card>)}</div></section>}
