packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.3'
  - '@tanstack/react-query@5.101.3'

onlyBuiltDependencies:
  - "sharp"
  - "unrs-resolver"
