from __future__ import annotations

import hashlib
import json
from datetime import datetime
from typing import Annotated
from urllib.error import HTTPError, URLError
from urllib.request import urlopen
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import text

from .auth import authenticated_principal
from .config import get_settings
from .database import DatabaseEngine, principal_transaction
from .object_storage import ObjectStorageConfigurationError, S3Presigner
from .resume_extraction import (
    MAX_RESUME_FILE_BYTES,
    ResumeExtractionError,
    extract_resume_text,
    validate_resume_upload_metadata,
)
from .schemas import AuthenticatedPrincipal, Role

router = APIRouter(prefix="/api/v1/career", tags=["career-os"])
_CURRENT_USER_SQL = "NULLIF(current_setting('rigor.user_id', true), '')::uuid"


class CareerResumeDocument(BaseModel):
    document_id: UUID
    candidate_file_id: UUID
    file_name: str
    mime_type: str
    extraction_method: str
    character_count: int
    created_at: datetime


def _require_candidate(principal: AuthenticatedPrincipal) -> None:
    if Role.candidate not in principal.roles:
        raise HTTPException(status_code=403, detail="CareerOS is available to candidate accounts")


def _download_resume_bytes(url: str) -> bytes:
    try:
        with urlopen(url, timeout=10) as response:  # noqa: S310 - generated by S3Presigner.
            content_length = response.headers.get("Content-Length")
            if content_length is not None and int(content_length) > MAX_RESUME_FILE_BYTES:
                raise ResumeExtractionError(
                    "resume_too_large",
                    "Stored resume exceeds the 8 MiB extraction limit.",
                )
            data = response.read(MAX_RESUME_FILE_BYTES + 1)
    except ResumeExtractionError:
        raise
    except (HTTPError, URLError, TimeoutError, OSError, ValueError) as exc:
        raise HTTPException(status_code=409, detail="Resume upload is not available yet.") from exc
    if len(data) > MAX_RESUME_FILE_BYTES:
        raise ResumeExtractionError(
            "resume_too_large",
            "Stored resume exceeds the 8 MiB extraction limit.",
        )
    return data


def _quarantine_file(
    engine: DatabaseEngine,
    principal: AuthenticatedPrincipal,
    file_id: UUID,
) -> None:
    with principal_transaction(engine, principal) as connection:
        connection.execute(
            text(
                f"""
                UPDATE candidate_files
                SET status='quarantined', updated_at=CURRENT_TIMESTAMP
                WHERE id=:file_id
                  AND user_id={_CURRENT_USER_SQL}
                  AND status <> 'deleted'
                """
            ),
            {"file_id": file_id},
        )


@router.post("/resumes/{file_id}/extract", response_model=CareerResumeDocument)
def extract_candidate_resume(
    file_id: UUID,
    engine: DatabaseEngine,
    principal: Annotated[AuthenticatedPrincipal, Depends(authenticated_principal)],
) -> CareerResumeDocument:
    _require_candidate(principal)
    settings = get_settings()
    if not settings.s3_upload_bucket:
        raise HTTPException(status_code=503, detail="Private file storage is not configured")

    with principal_transaction(engine, principal) as connection:
        file_row = connection.execute(
            text(
                f"""
                SELECT
                    f.id,
                    f.storage_key,
                    f.file_name,
                    f.mime_type,
                    f.size_bytes,
                    f.checksum_sha256,
                    f.category,
                    f.status,
                    d.id AS document_id,
                    d.candidate_file_id,
                    d.extraction_method,
                    d.raw_text,
                    d.created_at
                FROM candidate_files f
                LEFT JOIN career_documents d ON d.candidate_file_id=f.id
                WHERE f.id=:file_id
                  AND f.user_id={_CURRENT_USER_SQL}
                """
            ),
            {"file_id": file_id},
        ).mappings().one_or_none()

    if file_row is None:
        raise HTTPException(status_code=404, detail="Resume file not found")
    if file_row["document_id"] is not None:
        return CareerResumeDocument(
            document_id=file_row["document_id"],
            candidate_file_id=file_row["candidate_file_id"],
            file_name=file_row["file_name"],
            mime_type=file_row["mime_type"],
            extraction_method=file_row["extraction_method"],
            character_count=len(file_row["raw_text"]),
            created_at=file_row["created_at"],
        )
    if file_row["category"] != "resume":
        raise HTTPException(status_code=422, detail="Candidate file is not a resume")
    if file_row["status"] == "quarantined":
        raise HTTPException(status_code=409, detail="Resume file is quarantined")
    if file_row["status"] == "deleted":
        raise HTTPException(status_code=404, detail="Resume file not found")

    try:
        validate_resume_upload_metadata(
            file_row["file_name"],
            file_row["mime_type"],
            int(file_row["size_bytes"]),
        )
    except ResumeExtractionError as exc:
        _quarantine_file(engine, principal, file_id)
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    try:
        download_url = S3Presigner.from_environment(
            region=settings.aws_region,
            bucket=settings.s3_upload_bucket,
        ).presign(
            method="GET",
            storage_key=file_row["storage_key"],
            expires_seconds=60,
        )
    except ObjectStorageConfigurationError as exc:
        raise HTTPException(
            status_code=503,
            detail="Private file storage is misconfigured",
        ) from exc

    try:
        data = _download_resume_bytes(download_url)
        if len(data) != int(file_row["size_bytes"]):
            raise ResumeExtractionError(
                "resume_size_mismatch",
                "Uploaded resume size does not match the recorded upload metadata.",
            )
        checksum = file_row["checksum_sha256"]
        if checksum and hashlib.sha256(data).hexdigest().casefold() != str(checksum).casefold():
            raise ResumeExtractionError(
                "resume_checksum_mismatch",
                "Uploaded resume checksum does not match the recorded upload metadata.",
            )
        extracted = extract_resume_text(
            data,
            file_row["file_name"],
            file_row["mime_type"],
        )
    except ResumeExtractionError as exc:
        _quarantine_file(engine, principal, file_id)
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    content_sha256 = hashlib.sha256(extracted.text.encode("utf-8")).hexdigest()
    metadata = {
        **extracted.metadata,
        "source_size_bytes": len(data),
        "source_checksum_sha256": hashlib.sha256(data).hexdigest(),
    }
    with principal_transaction(engine, principal) as connection:
        row = connection.execute(
            text(
                f"""
                INSERT INTO career_documents (
                    user_id,
                    kind,
                    title,
                    raw_text,
                    content_sha256,
                    candidate_file_id,
                    extraction_method,
                    extraction_metadata
                ) VALUES (
                    {_CURRENT_USER_SQL},
                    'resume',
                    :title,
                    :raw_text,
                    :content_sha256,
                    :candidate_file_id,
                    :extraction_method,
                    CAST(:extraction_metadata AS jsonb)
                )
                ON CONFLICT (candidate_file_id)
                    WHERE candidate_file_id IS NOT NULL
                DO UPDATE SET
                    title=EXCLUDED.title,
                    raw_text=EXCLUDED.raw_text,
                    content_sha256=EXCLUDED.content_sha256,
                    extraction_method=EXCLUDED.extraction_method,
                    extraction_metadata=EXCLUDED.extraction_metadata
                RETURNING id, candidate_file_id, extraction_method, raw_text, created_at
                """
            ),
            {
                "title": file_row["file_name"],
                "raw_text": extracted.text,
                "content_sha256": content_sha256,
                "candidate_file_id": file_id,
                "extraction_method": extracted.extraction_method,
                "extraction_metadata": json.dumps(metadata),
            },
        ).mappings().one()
        connection.execute(
            text(
                f"""
                UPDATE candidate_files
                SET status='available', updated_at=CURRENT_TIMESTAMP
                WHERE id=:file_id
                  AND user_id={_CURRENT_USER_SQL}
                """
            ),
            {"file_id": file_id},
        )

    return CareerResumeDocument(
        document_id=row["id"],
        candidate_file_id=row["candidate_file_id"],
        file_name=file_row["file_name"],
        mime_type=file_row["mime_type"],
        extraction_method=row["extraction_method"],
        character_count=len(row["raw_text"]),
        created_at=row["created_at"],
    )
